BEGIN;

CREATE TABLE IF NOT EXISTS reservas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  protocolo TEXT UNIQUE NOT NULL,
  nome_cliente TEXT NOT NULL,
  telefone TEXT NOT NULL,
  servico TEXT NOT NULL,
  entrada DATE NOT NULL,
  saida DATE NOT NULL,
  quantidade_pets INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'aguardando_validacao',
  comprovante TEXT,
  pets_detalhe JSONB NOT NULL DEFAULT '[]'::jsonb,
  observacao TEXT,
  valor_total NUMERIC(10,2),
  data_criacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  data_atualizacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  hora_entrada TEXT,
  hora_saida TEXT,
  endereco TEXT,
  visitas_dia INTEGER,
  frequencia_semanal INTEGER,
  dias_semana JSONB NOT NULL DEFAULT '[]'::jsonb,
  quantidade_dias INTEGER,
  forma_pagamento TEXT NOT NULL DEFAULT 'pix',
  valor_sinal NUMERIC(10,2),
  valor_a_pagar NUMERIC(10,2),
  saldo_pendente NUMERIC(10,2),
  comprovante_nome TEXT,
  comprovante_mime TEXT,
  comprovante_caminho TEXT,
  comprovante_tamanho BIGINT,
  token_comprovante TEXT,
  token_validacao TEXT,
  data_expiracao TIMESTAMPTZ,
  data_confirmacao TIMESTAMPTZ,
  motivo_cancelamento TEXT,

  CONSTRAINT chk_reservas_protocolo CHECK (length(trim(protocolo)) >= 6),
  CONSTRAINT chk_reservas_nome CHECK (length(trim(nome_cliente)) >= 2),
  CONSTRAINT chk_reservas_telefone CHECK (length(trim(telefone)) >= 10),
  CONSTRAINT chk_reservas_servico CHECK (
    servico IN ('hospedagem_cao', 'hospedagem_gato', 'creche', 'domiciliar')
  ),
  CONSTRAINT chk_reservas_status CHECK (
    status IN ('pendente', 'aguardando_validacao', 'confirmado', 'cancelado', 'expirado')
  ),
  CONSTRAINT chk_reservas_pagamento CHECK (forma_pagamento = 'pix'),
  CONSTRAINT chk_reservas_pets CHECK (quantidade_pets >= 1),
  CONSTRAINT chk_reservas_periodo CHECK (saida >= entrada),
  CONSTRAINT chk_reservas_valor_total CHECK (valor_total IS NULL OR valor_total >= 0),
  CONSTRAINT chk_reservas_valor_sinal CHECK (valor_sinal IS NULL OR valor_sinal >= 0),
  CONSTRAINT chk_reservas_valor_pagar CHECK (valor_a_pagar IS NULL OR valor_a_pagar >= 0),
  CONSTRAINT chk_reservas_saldo CHECK (saldo_pendente IS NULL OR saldo_pendente >= 0)
);

CREATE TABLE IF NOT EXISTS validacao_tentativas (
  chave_hash TEXT PRIMARY KEY,
  inicio TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  tentativas INTEGER NOT NULL DEFAULT 0,
  bloqueado_ate TIMESTAMPTZ,
  CONSTRAINT chk_validacao_tentativas CHECK (tentativas >= 0)
);

CREATE TABLE IF NOT EXISTS reserva_dias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reserva_id BIGINT NOT NULL REFERENCES reservas(id) ON DELETE CASCADE,
  data DATE NOT NULL,
  UNIQUE (reserva_id, data)
);

ALTER TABLE reservas
  ADD COLUMN IF NOT EXISTS comprovante_tamanho BIGINT;

CREATE INDEX IF NOT EXISTS idx_reservas_disponibilidade
  ON reservas (status, servico, entrada, saida);
CREATE INDEX IF NOT EXISTS idx_reservas_protocolo
  ON reservas (protocolo);
CREATE INDEX IF NOT EXISTS idx_reservas_telefone
  ON reservas (telefone, protocolo);
CREATE INDEX IF NOT EXISTS idx_reserva_dias_data
  ON reserva_dias (data, reserva_id);
CREATE INDEX IF NOT EXISTS idx_validacao_tentativas_bloqueio
  ON validacao_tentativas (bloqueado_ate);
CREATE UNIQUE INDEX IF NOT EXISTS idx_reservas_comprovante_caminho
  ON reservas (comprovante_caminho)
  WHERE comprovante_caminho IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_reservas_token_comprovante
  ON reservas (token_comprovante)
  WHERE token_comprovante IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_reservas_token_validacao
  ON reservas (token_validacao)
  WHERE token_validacao IS NOT NULL;

COMMIT;
